name: 🐛 Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Package Version
      description: What version of @perseidesjs/auth-otp are you running?
      placeholder: e.g. 1.0.0-alpha.1
    validations:
      required: true

  - type: input
    id: medusa-version
    attributes:
      label: Medusa Version
      description: What version of Medusa are you running?
      placeholder: e.g. 2.5.0
    validations:
      required: true

  - type: dropdown
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you running?
      options:
        - 16.x
        - 18.x
        - 20.x
        - Other (specify in additional context)
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code.
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.